```{r setupenvsp, include=FALSE}
rm(list = ls()) ; invisible(gc()) ; set.seed(42)
library(knitr)
library(tidyverse)
theme_set(bayesplot::theme_default())
opts_chunk$set(
  echo = F, message = F, warning = F, fig.height = 6, fig.width = 8,
  cache = T, cache.lazy = F)
```

```{r make_fig_env}
make_fig <- function(file, n = 100){
  t <- vroom::vroom(file) 
  t %>% 
  filter(count > 0) %>% 
  filter(snp %in% sample(unique(t$snp), n)) %>% 
  ggplot(aes(individual, snp, fill = log10(count))) +
  geom_tile() +
  theme(axis.text = element_blank(), axis.ticks.y = element_blank(), axis.line = element_blank(),
        legend.position = "bottom") +
  xlab("Individual") + ylab("SNP") +
  facet_grid(~ variant + species, scales = "free_x", space = "free_x") +
  viridis::scale_fill_viridis(option = "C") +
  ggtitle(
    paste("N =", length(unique(t$snp)))
  )
}
```

# Environment-specific

> SNPs specific to the environment

## Single-SNPs 

```{r ssnpenvsp, fig.cap="Environment-specific single SNP with first 100 counts."}
make_fig("results/environment_specific_snps/results_coherent_type_0a.tsv")
```

## Multi-SNPs

```{r msnpenvsp, fig.cap="Environment-specific multi SNP with first 100 counts."}
make_fig("results/environment_specific_snps/results_coherent_type_0b.tsv")
```

## Alternative splicings

```{r altspenvsp, fig.cap="Environment-specific microsattelites with first 100 counts."}
make_fig("results/environment_specific_snps/results_coherent_type_1.tsv")
```

## Microsattelite

```{r msatenvsp, fig.cap="Environment-specific microsattelites."}
make_fig("results/environment_specific_snps/results_coherent_type_2.tsv", n = 3)
```

## Indels

```{r indelsenvsp, fig.cap="Environment-specific indels with first 100 counts."}
make_fig("results/environment_specific_snps/results_coherent_type_3.tsv")
```

## Others

```{r othersenvsp, fig.cap="Environment-specific other markers with first 100 counts."}
make_fig("results/environment_specific_snps/results_coherent_type_4.tsv")
```
